In [6]:
import numpy as np
from scipy import optimize
import math
import functools

In [7]:
B = 2.0
P = 2.0
T = 2.0
N = 1000.0
M = 32.0
E = 4.0
L = math.ceil(math.log((N*(T-1)/(P*B))+1, T))
print(L)

m_init = [0]*int(L)

def read_cost(B,P,T,N,E,m):
    return np.sum([((B*P*T**(i) - (B*P*T**(i))/(N-B*P) * m[0]/E)/N) \
                   * np.sum([.6185**(m[j]/B*P*T**(j)) for j in range(1,i)]) for i in range(1,len(m))])
    
cost_m = functools.partial(read_cost, B,P,T,N,E)

def constraint_gen(M, m):
    return np.atleast_1d(M - np.sum(np.abs(m)))

constraint_m = functools.partial(constraint_gen, M)

constraint_m(m_init)

8.0


array([ 32.])

In [49]:
result = optimize.fmin_slsqp(cost_m, np.array(m_init), ieqcons=[constraint_m, ])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 3.70333339017e-05
            Iterations: 31
            Function evaluations: 325
            Gradient evaluations: 31


In [42]:
result = optimize.fmin_slsqp(cost_m, result, ieqcons=[constraint_m, ])

Iteration limit exceeded    (Exit mode 9)
            Current function value: 0.000447111732841
            Iterations: 101
            Function evaluations: 1795
            Gradient evaluations: 101


/Users/soph/anaconda/envs/py27/lib/python2.7/site-packages/ipykernel/__main__.py:13: RuntimeWarning: overflow encountered in double_scalars


In [52]:
np.sum(np.round(result))

31.0

In [55]:
np.round(result)

array([ 9.,  4.,  7.,  3.,  1.,  0.,  0.,  7.])

In [8]:
cons = {'type':'ineq','fun': constraint_m}
minimizer_kwargs = {"method":"COBYLA","constraints":cons}

ret = optimize.basinhopping(cost_m,m_init,minimizer_kwargs=minimizer_kwargs)

In [9]:
ret

                        fun: 5.9112409655111076e-07
 lowest_optimization_result:      fun: 5.9112409655111076e-07
   maxcv: 0.00010429431350189589
 message: 'Optimization terminated successfully.'
    nfev: 169
  status: 1
 success: True
       x: array([ -1.16282758e-05,   1.56785090e+01,   8.17353077e+00,
         4.25101945e+00,   2.20034573e+00,   1.12216689e+00,
         5.74465121e-01,  -5.56988610e-05])
                    message: ['requested number of basinhopping iterations completed successfully']
      minimization_failures: 33
                       nfev: 18921
                        nit: 100
                          x: array([ -1.16282758e-05,   1.56785090e+01,   8.17353077e+00,
         4.25101945e+00,   2.20034573e+00,   1.12216689e+00,
         5.74465121e-01,  -5.56988610e-05])

In [3]:
m=[1,1,1,1,1,1]

print ([[j for j in range(1,i)] for i in range(1,len(m))])

[[], [1], [1, 2], [1, 2, 3], [1, 2, 3, 4]]


In [10]:
np.ceil(ret.x)

array([ -0.,  16.,   9.,   5.,   3.,   2.,   1.,  -0.])